### ISSUE TITLE
Dotcom library Design kit: add masthead L0

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm.com-design-kit#20]
_Olivia-Flory created the following on Sep 26:_  

 ### User story
As a designer, I need access to visual design symbols of the new masthead, so I can align my designs to the new standard.

### Notes
- Designers need to use the new masthead in their designs so they don't confuse the developers with the northstar masthead
- we need to include the masthead in a design kit 

#### Outstanding questions
- should it be included in the Expressive design kit?
- should the masthead be in a IBM.com library design kit?
- list of customizable pieces

### Tasks
- [x] identify which pieces of the masthead are customizable
- [x] figure out symbol structure
- [ ] cover all breakpoints
- [x] cover all variations
- [x] add symbols to design kit

### Acceptance criteria
- [ ] Symbols match design and code specifications
   - [ ] L0 base
   - [ ] L0 links
   - [ ] L0 dropdowns
   - [ ] L0 search expanded
- [ ] Design reviewed by Wonil / Lara
- [ ] Design approved Wonil / Lara 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1777_
