### ISSUE TITLE
Dotcom library Design kit: add masthead L1

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm.com-design-kit#21]
### User story
As a designer, I need access to the L1 symbol in order to implement it in my designs.

### Notes
Designers need to use the new masthead in their designs so they don't confuse the developers with the northstar masthead

### Tasks
 - [ ]  identify which pieces of the masthead are customizable
 - [ ] figure out symbol structure
 - [ ] cover all breakpoints
 - [ ] cover all variations
 - [ ] add symbols to design kit

### Acceptance criteria
- [ ] symbols match design and code specifications
   - [x] L1 base
   - [x] L1 page title options
   - [x] L1 links
   - [x] L1 dropdowns
- [x] Design reviewed by Wonil / Lara
- [ ] Design approved by Wonil / Lara
